import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { pathToFileURL } from 'url';

const isDirectRun =
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href;

const ROOT = process.cwd();
const PUBLISH_DIR = path.join(ROOT, 'content', 'publish');
const PUBLIC_DIR = path.join(ROOT, 'public');

const SITE_URL = process.env.SITE_URL || 'https://jagdishkumarpatel.github.io';

const STATIC_ROUTES = [
  '/',
  '/about/',
  '/blog/',
  '/projects/',
  '/certifications/',
  '/education/',
  '/contact/',
];

function isoDate(d) {
  try {
    if (!d) return undefined;
    const dt = new Date(d);
    if (isNaN(dt.getTime())) return undefined;
    return dt.toISOString();
  } catch {
    return undefined;
  }
}

function escapeXml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function normalizeSlug(dataSlug, file) {
  const raw = dataSlug || file.replace(/\.mdx?$/i, '');

  return raw
    .replace(/^\/blog\//, '')
    .replace(/^\/+/, '')
    .replace(/\/+$/, '');
}

function loadPosts() {
  if (!fs.existsSync(PUBLISH_DIR)) return [];

  const files = fs.readdirSync(PUBLISH_DIR).filter((f) => /\.mdx?$/i.test(f));

  const seen = new Set();

  const posts = [];

  for (const file of files) {
    const filePath = path.join(PUBLISH_DIR, file);
    const raw = fs.readFileSync(filePath, 'utf8');
    const { data } = matter(raw);

    const slug = normalizeSlug(data.slug, file);
    const urlPath = `/blog/${slug}/`;

    // ✅ prevent duplicates
    if (seen.has(urlPath)) continue;
    seen.add(urlPath);

    posts.push({
      loc: SITE_URL + urlPath,
      lastmod: isoDate(data.date),
      changefreq: 'weekly',
      priority: '0.7',
    });
  }

  // newest first
  posts.sort((a, b) => {
    const ta = a.lastmod ? Date.parse(a.lastmod) : 0;
    const tb = b.lastmod ? Date.parse(b.lastmod) : 0;
    return tb - ta;
  });

  return posts;
}

function buildUrlEntry({ loc, lastmod, changefreq, priority }) {
  return [
    '  <url>',
    `    <loc>${escapeXml(loc)}</loc>`,
    lastmod ? `    <lastmod>${escapeXml(lastmod)}</lastmod>` : null,
    changefreq ? `    <changefreq>${escapeXml(changefreq)}</changefreq>` : null,
    priority ? `    <priority>${escapeXml(priority)}</priority>` : null,
    '  </url>',
  ]
    .filter(Boolean)
    .join('\n');
}

async function main() {
  if (!fs.existsSync(PUBLIC_DIR)) {
    fs.mkdirSync(PUBLIC_DIR, { recursive: true });
  }

  const staticUrls = STATIC_ROUTES.map((route) => ({
    loc: SITE_URL + route,
    changefreq: 'monthly',
    priority: '0.6',
  }));

  const postUrls = loadPosts();

  const urls = [...staticUrls, ...postUrls];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.js -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(buildUrlEntry).join('\n')}
</urlset>`;

  const outPath = path.join(PUBLIC_DIR, 'sitemap.xml');
  fs.writeFileSync(outPath, xml, 'utf8');

  console.log(`✅ Sitemap generated → ${outPath}`);
  console.log(`📦 Total URLs: ${urls.length}`);
  console.log(`🌐 SITE_URL: ${SITE_URL}`);
}

if (isDirectRun) {
  try {
    await main();
  } catch (err) {
    console.error('❌ Sitemap generation failed:', err);
    process.exit(1);
  }
}